import { motion } from 'framer-motion';
import { HiSparkles } from 'react-icons/hi2';

interface AIAnalysisCardProps {
  title: string;
  content: string;
  confidence?: number;
  icon?: React.ReactNode;
}

/**
 * AIAnalysisCard — Premium card for displaying AI-generated analysis content
 */
export default function AIAnalysisCard({ title, content, confidence, icon }: AIAnalysisCardProps) {
  return (
    <motion.div
      className="glass-card"
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      style={{
        padding: '28px',
        position: 'relative',
        overflow: 'hidden',
        borderImage: 'linear-gradient(135deg, rgba(139,92,246,0.3), rgba(6,182,212,0.3)) 1',
        borderImageSlice: 1,
        border: '1px solid',
      }}
    >
      {/* AI Glow */}
      <div style={{
        position: 'absolute',
        top: -50,
        left: -50,
        width: 150,
        height: 150,
        borderRadius: '50%',
        background: 'linear-gradient(135deg, var(--accent-purple), var(--accent-cyan))',
        opacity: 0.04,
        filter: 'blur(50px)',
      }} />

      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 16 }}>
        <div style={{
          width: 36,
          height: 36,
          borderRadius: 10,
          background: 'linear-gradient(135deg, rgba(139,92,246,0.2), rgba(6,182,212,0.2))',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          color: 'var(--accent-purple)',
        }}>
          {icon || <HiSparkles size={18} />}
        </div>
        <div>
          <h3 style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--text-primary)' }}>{title}</h3>
          {confidence !== undefined && (
            <span style={{ fontSize: '0.7rem', color: 'var(--accent-cyan)' }}>
              {confidence}% confidence
            </span>
          )}
        </div>
      </div>

      {/* Content */}
      <p style={{
        fontSize: '0.9rem',
        color: 'var(--text-secondary)',
        lineHeight: 1.7,
      }}>
        {content}
      </p>

      {/* AI badge */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        gap: 6,
        marginTop: 16,
        paddingTop: 16,
        borderTop: '1px solid rgba(255,255,255,0.05)',
      }}>
        <HiSparkles size={12} color="var(--accent-purple)" />
        <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>Generated by AirSense AI Engine</span>
      </div>
    </motion.div>
  );
}
